import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/Hero/Hero";
import Partner from "@/components/Partners/Partner";
import Value from "@/components/Value/Value";
import Courses from "@/components/Courses/Courses";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Talent Plus</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Hero />
				<Partner />
				<Value />
				<Courses />
			</main>
		</>
	);
}
